# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Sun Jan  2 14:10:59 2011
#      by: PyQt4 UI code generator 4.7.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(268, 647)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logoLabel = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.logoLabel.sizePolicy().hasHeightForWidth())
        self.logoLabel.setSizePolicy(sizePolicy)
        self.logoLabel.setMinimumSize(QtCore.QSize(0, 70))
        self.logoLabel.setObjectName("logoLabel")
        self.verticalLayout_3.addWidget(self.logoLabel)
        self.loginWidget = QtGui.QWidget(self.centralwidget)
        self.loginWidget.setObjectName("loginWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.loginWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.loginWidget)
        self.label.setMinimumSize(QtCore.QSize(68, 27))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.usernameEdit = QtGui.QLineEdit(self.loginWidget)
        self.usernameEdit.setMinimumSize(QtCore.QSize(156, 27))
        self.usernameEdit.setObjectName("usernameEdit")
        self.horizontalLayout.addWidget(self.usernameEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.loginWidget)
        self.label_2.setMinimumSize(QtCore.QSize(68, 27))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.passwordEdit = QtGui.QLineEdit(self.loginWidget)
        self.passwordEdit.setMinimumSize(QtCore.QSize(156, 27))
        self.passwordEdit.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_2.addWidget(self.passwordEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.loginButton = QtGui.QPushButton(self.loginWidget)
        self.loginButton.setObjectName("loginButton")
        self.horizontalLayout_3.addWidget(self.loginButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addWidget(self.loginWidget)
        self.clientWidget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clientWidget.sizePolicy().hasHeightForWidth())
        self.clientWidget.setSizePolicy(sizePolicy)
        self.clientWidget.setObjectName("clientWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.clientWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.usernameLabel = QtGui.QLabel(self.clientWidget)
        self.usernameLabel.setStyleSheet("font: 75 10pt \"Arial Black\";")
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_2.addWidget(self.usernameLabel)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.statusEdit = QtGui.QLineEdit(self.clientWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusEdit.sizePolicy().hasHeightForWidth())
        self.statusEdit.setSizePolicy(sizePolicy)
        self.statusEdit.setStyleSheet("color: rgb(99, 99, 99);\n"
"font: italic 7pt \"Arial\";")
        self.statusEdit.setObjectName("statusEdit")
        self.horizontalLayout_4.addWidget(self.statusEdit)
        self.setStatusButton = QtGui.QPushButton(self.clientWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setStatusButton.sizePolicy().hasHeightForWidth())
        self.setStatusButton.setSizePolicy(sizePolicy)
        self.setStatusButton.setMaximumSize(QtCore.QSize(41, 16777215))
        self.setStatusButton.setObjectName("setStatusButton")
        self.horizontalLayout_4.addWidget(self.setStatusButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.buddyList = QtGui.QListWidget(self.clientWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buddyList.sizePolicy().hasHeightForWidth())
        self.buddyList.setSizePolicy(sizePolicy)
        self.buddyList.setMinimumSize(QtCore.QSize(0, 300))
        self.buddyList.setObjectName("buddyList")
        self.verticalLayout_2.addWidget(self.buddyList)
        self.verticalLayout_3.addWidget(self.clientWidget)
        spacerItem2 = QtGui.QSpacerItem(20, 45, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 268, 23))
        self.menubar.setObjectName("menubar")
        self.menu_Help = QtGui.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        self.menuXScribble = QtGui.QMenu(self.menubar)
        self.menuXScribble.setObjectName("menuXScribble")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLogout = QtGui.QAction(MainWindow)
        self.actionLogout.setObjectName("actionLogout")
        self.menu_Help.addAction(self.actionAbout)
        self.menuXScribble.addAction(self.actionLogout)
        self.menubar.addAction(self.menuXScribble.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())
        self.label.setBuddy(self.usernameEdit)
        self.label_2.setBuddy(self.passwordEdit)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "xScribble", None, QtGui.QApplication.UnicodeUTF8))
        self.logoLabel.setText(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/images/logo.png\" /></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Password ", None, QtGui.QApplication.UnicodeUTF8))
        self.loginButton.setText(QtGui.QApplication.translate("MainWindow", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameLabel.setText(QtGui.QApplication.translate("MainWindow", "xScribble User", None, QtGui.QApplication.UnicodeUTF8))
        self.statusEdit.setText(QtGui.QApplication.translate("MainWindow", "Scribbling in Colors", None, QtGui.QApplication.UnicodeUTF8))
        self.setStatusButton.setText(QtGui.QApplication.translate("MainWindow", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Help.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuXScribble.setTitle(QtGui.QApplication.translate("MainWindow", "xScribble", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About xScribble", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLogout.setText(QtGui.QApplication.translate("MainWindow", "Logout", None, QtGui.QApplication.UnicodeUTF8))

import xscribble_rc
